# https://github.com/elastic/elasticsearch-docker
FROM docker pull docker.elastic.co/elasticsearch/elasticsearch:7.0.0

RUN chmod -R 0777 /usr/share/elasticsearch

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
